name: GLink
on:
  workflow_dispatch: 
  issues:
    types:
      - opened
      - reopened
permissions: write-all
jobs:
  build:
    name: 'See progress'
    runs-on: ubuntu-latest
    env:
      NUMBIE: ${{ github.event.issue.number }}
      GH_TOKEN: ${{ github.token }}
      URL: ${{ inputs.URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Start process'
        run: |
          # Kakathic         
          # bash .github/GLink.sh 2>&1 | tee -a log.txt
          mkdir -p test
          sudo mount -r -t erofs -o loop .github/mi_ext.img test
          ls -1 test
          
          
